[package]
name = "problem845"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.44.0"
num = "0.4.1"
num-bigint = "0.4.3"
num-traits = "0.2.16"
